PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
  User_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Role TEXT NOT NULL,
  Username TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL,
  Permissions TEXT DEFAULT '{}',
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Clients (
  Client_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Full_Name TEXT NOT NULL,
  Phone_Number TEXT,
  Rating INTEGER DEFAULT 3,
  Total_Spent REAL DEFAULT 0,
  Notes TEXT,
  Created_By INTEGER,
  Agent_Commission REAL DEFAULT 0,
  Agent_ID INTEGER,
  Assigned_At TEXT DEFAULT CURRENT_TIMESTAMP,
  Source TEXT,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Created_By) REFERENCES Users(User_ID),
  FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Inventory (
  Material_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Material_Name TEXT NOT NULL,
  Thickness TEXT,
  Quantity REAL DEFAULT 0,
  Cost_Per_Unit REAL DEFAULT 0,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Orders (
  Task_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Client_ID INTEGER NOT NULL,
  Designer_ID INTEGER,
  Created_By INTEGER,
  Machine_Type TEXT NOT NULL,
  Status TEXT NOT NULL DEFAULT 'قيد التصميم',
  Approval_Status TEXT DEFAULT 'approved',
  Material_ID INTEGER,
  Material_Qty REAL DEFAULT 0,
  Quantity_Unit TEXT DEFAULT 'لوح',
  Inventory_Deducted_At TEXT,
  Price REAL DEFAULT 0,
  Cost REAL DEFAULT 0,
  Profit REAL DEFAULT 0,
  Agent_Price REAL DEFAULT 0,
  Agent_Commission REAL DEFAULT 0,
  Final_Price REAL DEFAULT 0,
  Agent_Approved_At TEXT,
  Agent_Approved_By INTEGER,
  File_Path TEXT,
  File_Name TEXT,
  Notes TEXT,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  Updated_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Client_ID) REFERENCES Clients(Client_ID),
  FOREIGN KEY (Designer_ID) REFERENCES Users(User_ID),
  FOREIGN KEY (Created_By) REFERENCES Users(User_ID),
  FOREIGN KEY (Material_ID) REFERENCES Inventory(Material_ID)
);

CREATE TABLE IF NOT EXISTS Order_Materials (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Task_ID INTEGER NOT NULL,
  Material_ID INTEGER NOT NULL,
  Quantity REAL DEFAULT 0,
  FOREIGN KEY (Task_ID) REFERENCES Orders(Task_ID) ON DELETE CASCADE,
  FOREIGN KEY (Material_ID) REFERENCES Inventory(Material_ID)
);

CREATE TABLE IF NOT EXISTS Order_Files (
  File_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Task_ID INTEGER NOT NULL,
  Original_Name TEXT NOT NULL,
  Stored_Name TEXT NOT NULL,
  File_Path TEXT NOT NULL,
  File_Size REAL DEFAULT 0,
  Label TEXT DEFAULT '',
  File_Type TEXT DEFAULT 'design',
  Upload_Type TEXT DEFAULT 'design',
  Is_Current INTEGER DEFAULT 1,
  Uploaded_By INTEGER,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Task_ID) REFERENCES Orders(Task_ID) ON DELETE CASCADE,
  FOREIGN KEY (Uploaded_By) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Designs (
  Design_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Category TEXT DEFAULT '', Material TEXT DEFAULT '', Thickness TEXT DEFAULT '',
  Width REAL DEFAULT 0, Height REAL DEFAULT 0, Unit TEXT DEFAULT 'سم', Notes TEXT DEFAULT '',
  FilePath TEXT NOT NULL, Original_Name TEXT NOT NULL, ThumbnailPath TEXT,
  Password TEXT, CreatedBy INTEGER, CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CreatedBy) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Design_Permissions (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Design_ID INTEGER NOT NULL, User_ID INTEGER NOT NULL,
  FOREIGN KEY (Design_ID) REFERENCES Designs(Design_ID) ON DELETE CASCADE,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
  UNIQUE(Design_ID, User_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Images (
  Image_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Category TEXT NOT NULL DEFAULT 'عام', Original_Name TEXT NOT NULL, Stored_Name TEXT NOT NULL,
  File_Path TEXT NOT NULL, File_Size REAL DEFAULT 0, Uploaded_By INTEGER,
  Design_ID INTEGER, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Uploaded_By) REFERENCES Users(User_ID),
  FOREIGN KEY (Design_ID) REFERENCES Designs(Design_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Image_Materials (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Image_ID INTEGER NOT NULL, Material_ID INTEGER NOT NULL,
  FOREIGN KEY (Image_ID) REFERENCES Agent_Images(Image_ID) ON DELETE CASCADE,
  FOREIGN KEY (Material_ID) REFERENCES Inventory(Material_ID), UNIQUE(Image_ID, Material_ID)
);

CREATE TABLE IF NOT EXISTS Product_Pricing (
  Pricing_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Product_Name TEXT NOT NULL, Category TEXT DEFAULT 'عام', Base_Price REAL NOT NULL DEFAULT 0,
  Unit TEXT DEFAULT 'لوح', Description TEXT, Is_Active INTEGER DEFAULT 1,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP, Updated_At TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Product_Material_Pricing (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Pricing_ID INTEGER NOT NULL, Material_ID INTEGER NOT NULL, Price REAL NOT NULL DEFAULT 0,
  Is_Active INTEGER DEFAULT 1,
  FOREIGN KEY (Pricing_ID) REFERENCES Product_Pricing(Pricing_ID) ON DELETE CASCADE,
  FOREIGN KEY (Material_ID) REFERENCES Inventory(Material_ID), UNIQUE(Pricing_ID, Material_ID)
);

CREATE TABLE IF NOT EXISTS Client_Pricing (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Client_ID INTEGER NOT NULL, Pricing_ID INTEGER NOT NULL, Agent_Price REAL NOT NULL,
  Agent_Commission REAL DEFAULT 0, Final_Price REAL NOT NULL, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Client_ID) REFERENCES Clients(Client_ID) ON DELETE CASCADE,
  FOREIGN KEY (Pricing_ID) REFERENCES Product_Pricing(Pricing_ID) ON DELETE CASCADE,
  UNIQUE(Client_ID, Pricing_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Profiles (
  Agent_ID INTEGER PRIMARY KEY AUTOINCREMENT, User_ID INTEGER UNIQUE NOT NULL,
  Phone TEXT, Email TEXT, Territory TEXT, Commission_Rate REAL DEFAULT 0.10,
  Status TEXT DEFAULT 'active', Hired_Date TEXT DEFAULT CURRENT_DATE, Notes TEXT,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Custom_Designs (
  Custom_Design_ID INTEGER PRIMARY KEY AUTOINCREMENT, Agent_ID INTEGER NOT NULL,
  Order_ID INTEGER, Name TEXT NOT NULL, Description TEXT, Image_Path TEXT, Thumbnail_Path TEXT,
  Status TEXT DEFAULT 'pending', Designer_ID INTEGER, Notes TEXT,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP, Updated_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID), FOREIGN KEY (Order_ID) REFERENCES Orders(Task_ID),
  FOREIGN KEY (Designer_ID) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Notifications (
  Notif_ID INTEGER PRIMARY KEY AUTOINCREMENT, Task_ID INTEGER, Message TEXT NOT NULL,
  Type TEXT DEFAULT 'info', Is_Read INTEGER DEFAULT 0, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Task_ID) REFERENCES Orders(Task_ID)
);

CREATE TABLE IF NOT EXISTS Invoices (
  Invoice_ID INTEGER PRIMARY KEY AUTOINCREMENT, Order_Task_ID INTEGER NOT NULL,
  Client_ID INTEGER NOT NULL, Invoice_Number TEXT UNIQUE NOT NULL, Amount REAL NOT NULL,
  Amount_Paid REAL DEFAULT 0, Payment_Method TEXT DEFAULT 'نقداً', Status TEXT DEFAULT 'مدفوعة',
  Notes TEXT, File_Path TEXT, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Order_Task_ID) REFERENCES Orders(Task_ID), FOREIGN KEY (Client_ID) REFERENCES Clients(Client_ID)
);

CREATE TABLE IF NOT EXISTS Receipts (
  Receipt_ID INTEGER PRIMARY KEY AUTOINCREMENT, Receipt_Number TEXT UNIQUE NOT NULL,
  Order_Task_ID INTEGER NOT NULL, Client_ID INTEGER NOT NULL, Amount REAL DEFAULT 0,
  Notes TEXT, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Order_Task_ID) REFERENCES Orders(Task_ID), FOREIGN KEY (Client_ID) REFERENCES Clients(Client_ID)
);

CREATE TABLE IF NOT EXISTS Expenses (
  Expense_ID INTEGER PRIMARY KEY AUTOINCREMENT, Description TEXT NOT NULL,
  Category TEXT NOT NULL DEFAULT 'أخرى', Amount REAL NOT NULL, Expense_Date TEXT NOT NULL,
  Notes TEXT, Created_At TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Agent_Shapes (
  Shape_ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Description TEXT,
  Image_ID INTEGER, Created_At TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Image_ID) REFERENCES Agent_Images(Image_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Agent_Stats (
  Stat_ID INTEGER PRIMARY KEY AUTOINCREMENT, Agent_ID INTEGER NOT NULL, Stat_Date TEXT NOT NULL,
  Period_Type TEXT, Orders_Count INTEGER DEFAULT 0, Total_Sheets REAL DEFAULT 0,
  Total_Revenue REAL DEFAULT 0, Total_Commission REAL DEFAULT 0, Pending_Orders INTEGER DEFAULT 0,
  Approved_Orders INTEGER DEFAULT 0, Rejected_Orders INTEGER DEFAULT 0, New_Clients INTEGER DEFAULT 0,
  Active_Clients INTEGER DEFAULT 0, UNIQUE(Agent_ID, Stat_Date, Period_Type),
  FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Commissions (
  Commission_ID INTEGER PRIMARY KEY AUTOINCREMENT, Agent_ID INTEGER NOT NULL, Order_ID INTEGER,
  Client_ID INTEGER, Commission_Amount REAL NOT NULL, Commission_Type TEXT, Status TEXT DEFAULT 'pending',
  Calculated_At TEXT DEFAULT CURRENT_TIMESTAMP, Approved_At TEXT, Approved_By INTEGER, Paid_At TEXT, Notes TEXT,
  FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID), FOREIGN KEY (Order_ID) REFERENCES Orders(Task_ID),
  FOREIGN KEY (Client_ID) REFERENCES Clients(Client_ID), FOREIGN KEY (Approved_By) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Payouts (
  Payout_ID INTEGER PRIMARY KEY AUTOINCREMENT, Agent_ID INTEGER NOT NULL, Amount REAL NOT NULL,
  Period_Start TEXT NOT NULL, Period_End TEXT NOT NULL, Status TEXT DEFAULT 'pending',
  Payment_Method TEXT, Transaction_Ref TEXT, Requested_At TEXT DEFAULT CURRENT_TIMESTAMP,
  Processed_At TEXT, Processed_By INTEGER, Notes TEXT,
  FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID), FOREIGN KEY (Processed_By) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS Agent_Activity_Log (
  Log_ID INTEGER PRIMARY KEY AUTOINCREMENT, Agent_ID INTEGER NOT NULL, Action TEXT NOT NULL,
  Entity_Type TEXT, Entity_ID INTEGER, Details TEXT, IP_Address TEXT, User_Agent TEXT,
  Created_At TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (Agent_ID) REFERENCES Users(User_ID)
);

CREATE TABLE IF NOT EXISTS System_Logs (
  Log_ID INTEGER PRIMARY KEY AUTOINCREMENT, Action TEXT NOT NULL, User_ID INTEGER,
  Details TEXT, Created_At TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON Orders(Status, Approval_Status, Created_At);
CREATE INDEX IF NOT EXISTS idx_orders_client ON Orders(Client_ID, Created_At);
CREATE INDEX IF NOT EXISTS idx_order_files_task ON Order_Files(Task_ID, File_Type, Is_Current);
CREATE INDEX IF NOT EXISTS idx_agent_images_design ON Agent_Images(Design_ID);
